### ISSUE TITLE
Build periodically on Travis-CI

### ISSUE THREAD

**Issue by parasyte** [rust-console/cargo-n64#7]
I was just informed that the `hello-ipl3font` example is currently failing to build. That should be fixed, but I also want to be notified of when a build starts to break (usually due to changes in the nightly compiler or dependencies).

I'm not always active on every project, so periodic builds will be necessary. Even though it creates interrupt-driven development cycles... 😉

**Comment by Lokathor** [comment]
on the main part of the repository settings in travisCI you can set a 1/month scheduled build

**Comment by parasyte** [comment]
Yep! Sure can! The work here is to copy-pasta a `travis.yml` into the repo.
